return {
    "mason-org/mason.nvim",
    opts_extends = { "ensure_installed" },
    opts = {
        ensure_installed = {
            "ansible-language-server",
            "ansible-lint",
            "bash-language-server",
            "debugpy",
            "docker-compose-language-service",
            "dockerfile-language-server",
            "hadolint",
            "js-debug-adapter",
            "json-lsp",
            "lua-language-server",
            "markdown-toc",
            "markdownlint-cli2",
            "marksman",
            "php-cs-fixer",
            "php-debug-adapter",
            "phpactor",
            "phpcs",
            "pyright",
            "ruff",
            "shfmt",
            "sqlfluff",
            "stylua",
            "tailwindcss-language-server",
            "termux-language-server",
            "vtsls",
            "yaml-language-server",
        },
    },
}
